name: check

on:
  push: {}

jobs:
  spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: savi-lang/action-install@v1.0.0
      - run: savi run spec

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: savi-lang/action-install@v1.0.0
      - run: savi format --check
